// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hctzkrxxxoetwspbedgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjdHprcnh4eG9ldHdzcGJlZGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDAyNjMsImV4cCI6MjA2MTUxNjI2M30.bww-4pVhhGzCiUwGEumge2Gm83hOXkP2YdqeD21pHgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);